---

- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Add TCP firewall
  shell: 
    cmd: ufw allow 8300,8301,8302,8400,8500,8502,8600/tcp

- name: Add UDP firewall
  shell: 
    cmd: ufw allow 8301,8302,8502,8600/udp

- shell:
    cmd: iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600

- shell:
    cmd: iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600 

- shell:
    cmd: iptables --table nat --append OUTPUT --destination localhost --protocol udp --match udp --dport 53 --jump REDIRECT --to-ports 8600

- shell:
    cmd: iptables --table nat --append OUTPUT --destination localhost --protocol tcp --match tcp --dport 53 --jump REDIRECT --to-ports 8600

- shell:
    cmd: iptables-save

- name: Reload Firewall
  shell:
    cmd: ufw reload
