---
# tasks file for roles/Vault

- name: Update all packages to the latest version
  apt:
    upgrade: full
  become: true  

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true
  
- name: Install Vault
  apt:
    name: vault
    state: latest
  become: true

- name: Update Firewall
  include_tasks: firewalld.yml   

- name: Create Directory
  include_tasks: dir.yml   

- name: Upload File
  include_tasks: upload-file.yml 

- name: Enable and restart Vault
  service:
    name: vault
    state: restarted
    enabled: yes
  become: true

- name: Init Vault
  include_tasks: init-vault.yml
  run_once: true

- name: Unseal Vault
  include_tasks: unseal-vault.yml
