---

- name: Install Nomad
  apt:
    name: nomad
    state: latest

- name: Get CNI plugins release
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /var/cache/cni-plugins.tgz

- name: Create CNI plugins directory
  file:
    path: /opt/cni/bin
    state: directory
    owner: root
    group: root
    mode: 0775

- name: "Extract CNI plugins"
  unarchive:
    src: /var/cache/cni-plugins.tgz
    remote_src: true
    dest: /opt/cni/bin
    creates: /opt/cni/bin/bridge