---
# tasks file for nomad

- name: Update all packages to the latest version
  apt:
    upgrade: full 

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install Nomad
  include_tasks: install.yml

- name: Update Firewall
  include_tasks: firewalld.yml

- name: Create Directory
  include_tasks: dir.yml

- name: Config Nomad
  include_tasks: config.yml  

- name: Make sure nomad service is running
  systemd:
    name: nomad
    daemon_reload: true
    state: started
    enabled: true
