
- hosts: local
  roles:
    - TF-Vault

- hosts: local
  roles:
    - TF-Consul

- hosts: local
  roles:
    - TF-Storage

- hosts: local
  roles:
    - TF-Nomad

- hosts: ConsulServer
  become: true
  roles:
    - Consul-Server

- hosts: local
  tasks:
  - name: Grep the Bootstrap Token
    shell: ssh cloudmgr@172.20.8.236 "sed -n '/SecretID:/p' /etc/consul.d/.acl_bootstrap/acl-token | cut -d' ' -f10"
    register: token

  - community.general.terraform:
      project_path: "/home/adrien/Terraform/Ubuntu-Linux/Consul-Policy"
      state: present
      variables: 
        consul_token: "{{ token.stdout }}"
      backend_config_files:
        - "/home/adrien/Terraform/Ubuntu-Linux/Consul-Policy/credMinIO.json"

- hosts: Vault
  roles:
    - Vault
    - Consul-Agent

# - hosts: Storage
#   become: true 
#   roles:
#     - Storage
#     - Consul-Agent 

- hosts: NomadServer, NomadWorker
  become: true
  roles:
    - Nomad-VM
    - Consul-Agent 

- hosts: NomadWorker
  become: true
  roles:
    - NomadW-Soft
